# Generated by Django 5.2.17 on 2026-10-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cooking_time_minutes', models.PositiveIntegerField(default=30)),
                ('portions_saved', models.PositiveIntegerField(default=1)),
                ('ingredients_saved_kg', models.FloatField(default=0.2)),
                ('protein_grams', models.PositiveIntegerField(default=10)),
                ('calories_kcal', models.PositiveIntegerField(default=300)),
                ('status', models.CharField(choices=[('SAVED', 'Saved Meal'), ('HISTORY', 'History / Cooked')], default='SAVED', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
